# Repository
themeURL: https://github.com/bowman2001/perplex
docURL: https://github.com/bowman2001/perplexdoc
themeIssueTree: issues

# All parameters may be set per page in the front-matter
subtitle: false
toc: true
toctitle: On this Page
latex: false
mermaid: false

paginateNr: 5

taxonomies:
  tag: tags

# Image processing
imaging:
  u_number: 6 # Number of different sizes
  u_pxdmax: 4 # Maximum pixel density
  # JPEG Quality reduction for higher densities
  u_jpeg_quality_reduction: [-10, -20, -30]

# The following parameters of the Perplex layout are essential for image processing
# DO NOT REMOVE OR CHANGE THEM! THE LAYOUT WILL BREAK!
layout:
  measure: 70.0
  column: 33.0
  gutter: 4.0
  lineheightfac: 3.0
  guttermobile: 2.0
  xminmobile: 7.5
  xmaxmobile: 8.29
  xmin: 6.6667
  xmax: 10.0
  background: '#fffefd'
