### WARNING!
### This is the theme configuration file. Don’t change anything here!
### Use the configuration in your project root to change parameters.

## Theme parameters
params:
  
  # All parameters may be set per page in the front-matter
  subtitle    : false
  toc         : true
  toctitle    : On this Page
  latex       : false
  latex_dollar: true
  mermaid     : false
  svg         : inline
  
  paginateNr  : 5
  
  ### Default taxonomies the theme can handle
  taxonomies  :
    tag     : tags
    category: categories
    series  : series
  
  ### Official values for the link '<a>' attributes
  link:
    target: [_blank, _parent, _self, _top]
    rel: [alternate, author, bookmark, external, help, license, next, nofollow, noopener, noreferrer, opener, prev, search, tag]

  ### TOC walk fragments
  toc:
    startLevel: 2      # default is 2
    endLevel: 4        # default is 3
    minNumHeadings: 2  # default is 2

  ### Render hook link
  render_hooks:
    link:
      errorLevel: warning # ignore, warning, or error
    fragments:
      errorLevel: warning # ignore, or warning

  #### Image processing
  
  ### Parameters
  imaging     :
    fallback_width : 1400 # In pixel, also used for meta images
    sizestep       : 50 # In percent
    min_width      : 100 # In pixel
    # Quality reduction for higher densities
    # quality_reduction: [ -10, -20, -30 ] TODO
    
    ### WARNING!
    ### Changing the following parameters in your own config will break things.
    
    # See https://gohugo.io/content-management/image-processing/#anchor
    anchors        : [ Smart, TopLeft, Top, TopRight, Left, Center, Right, BottomLeft, Bottom, BottomRight ]
    no_processing  : [ svg, gif ]
    raster_compress: [ bmp, jpeg, webp ]
    raster_lossless: [ tiff, png ]
    rotate         : [ 90right, 90left, flip ]
    webp_hints     : [ drawing, icon, photo, picture, text ]
    rs_filter      : [ bartlett, blackman, box, bspline, catmullrom, cosine, gaussian, hamming, hann, hermite, lanczos, linear, mitchellnetravali, nearestneighbor, welch ]
    embedded       :
      size: [ tiny, small, normal, full ]
      posh: [ left, right ]
      posv: [ top, middle ]
    figure         :
      size: [ tiny, small, medium, normal, large, xlarge ]
      posh: [ left, center, right ]
      posv: [ top, middle ]
  
  layout      :
    measure      : 70.0
    column       : 33.0
    gutter       : 4.0
    lineheightfac: 3.0
    guttermobile : 2.0
    xminmobile   : 8.0
    xmaxmobile   : 8.5
    xmin         : 6.6667
    xmax         : 10.0
    background   : '#ffffff'

### Markup

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: true
      unsafe: false
      xhtml: false

### IMPORTANT!
### This module configuration does only affect the folder of the theme.
module  :

  hugoVersion:
    extended: false
    min: "0.111.3"

  imports:
    - path  : github.com/bowman2001/hugo-mod-replacements
      mounts:
        - source: partials
          target: layouts/partials
    - path  : github.com/bowman2001/hugo-mod-meta
      mounts:
        - source: partials
          target: layouts/partials
    - path: github.com/bowman2001/hugo-mod-open-in-vscode
      mounts:
        - source: partials
          target: layouts/partials
  
  mounts :
    - source: archetypes
      target: archetypes
    
    - source: assets
      target: assets
    
    - source: layouts
      target: layouts
    
    - source: static
      target: static

### The following loose security settings affect only the maintenance of this theme
### They don’t affect the security settings of a project using this theme!
### Hugo doesn’t merge security settings at all for obvious reasons.

security:
  enableInlineShortcodes: false
  exec                  :
    allow:
      - ^go$
    osEnv:
      - '.*'
      # - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|DISPLAY)$
  funcs                 :
    getenv:
      - ^HUGO_
      - ^GO
  http                  :
    methods:
      - (?i)GET|POST
    urls   :
      - .*
